### ISSUE TITLE
testing code with help of travis-ci.org

### ISSUE THREAD

**Issue by palica** [haxmeister/funtoo-reporter#101]
@haxmeister could you login to travis-ci.org and add this repo for testing and add the file that is in the PR (for feature/test-suite branch)

this would allow to test each PR before we merge it. and also every merge to master branch after merge. will do more work once the tests are more complete.

**Comment by palica** [comment]
http://laminar.liguros.net/jobs/funtoo-report/12

how an on-demand script working here

**Comment by palica** [comment]
less verbose one here
http://laminar.liguros.net/jobs/funtoo-report/14

going to start a hourly build/test job

**Comment by haxmeister** [comment]
https://travis-ci.org/profile/haxmeister

**Comment by palica** [comment]
can not view your profile like that :(

**Comment by palica** [comment]
but can view branches as they get tested. so can be closed
