### ISSUE TITLE
create and use a version-bumping script

### ISSUE THREAD

**Issue by palica** [haxmeister/funtoo-reporter#102]
I have found this for example:

https://github.com/cinch-financial/bump-version
or
https://github.com/colinJohnston/bump-version/blob/master/bump-version.sh

and others
https://github.com/search?l=Shell&q=bump_version&type=Repositories&utf8=%E2%9C%93

It would allow to do the last commit before release where we would update the versions on all files and add a Changelog entry with version and release date or something like that.

I don't know if we can do it some other way? Someone mentioned "generate all from POD" on IRC ...

Let me know if this is needed/wanted?

**Comment by ShadowM00n** [comment]
The concept seems interesting and sensible. When we get to the point where we're focusing more on the documentation, including the POD generation, this would be a good thing to also look at.

**Comment by palica** [comment]
@ShadowM00n could you please implement support for a string supplied in format v2.0.0-70-gabcdef2

`./bump_version.sh v2.0.0-70-gabcdef2`

and change https://github.com/haxmeister/funtoo-reporter/blob/feature/version-bumping-script/lib/Funtoo/Report.pm#L43 to support this modification?

it would allow to see which commit is in fundev index in ES/Kibana.

Thank you!

**Comment by palica** [comment]
it could also be an extra option like:
`./bump_version.sh describe`

**Comment by palica** [comment]
here you can see the 9999 ebuild for the tool.

https://liguros.net/zerobin/?e74b3d6197df753a#E8OH/e+8Lx0OaT7/qLfyHDdtiAtss+bFq8kzKI7nNeQ=

I would like to modify the version upon install to be able to directly see it then in ES index name. And also to be able to see which commit the tool is at when asking for `funtoo-report --version`
But only for 9999 (live/develop) ebuild.

Does it make sense?

So then the index in ES would be `fundev-2.0.0-70-gabcdef2-2018.04.08`

**Comment by ShadowM00n** [comment]
If I understood you correctly, I think the above commit should do that.

**Comment by palica** [comment]
ok, this should be ready to merge into develop and close.
