### ISSUE TITLE
omit hardware-info.networking.veth* stuff

### ISSUE THREAD

**Issue by palica** [haxmeister/funtoo-reporter#106]
can you guys, remove veth stuff from the report? it is just taking up field space with no actual value.
Thank you

**Comment by ShadowM00n** [comment]
I think that's all it takes; let me know if I overlooked something dumb.

**Comment by palica** [comment]
looks good. no veth interfaces visible here 
https://elk.liguros.net/app/kibana#/doc/54ff7ec0-361a-11e8-9d0c-f7ff098e3d37/fundev-3.0.0-beta-2018.04.07/report?id=sgIWomIBo3plbojXbeWE

if you are also happy, can be merged to develop.

**Comment by ShadowM00n** [comment]
Ok, will attempt to do so.

**Comment by ShadowM00n** [comment]
Alright, I think that worked so I'll go ahead and close this.
