### ISSUE TITLE
Add comment with current version to /etc/funtoo-report.conf file 

### ISSUE THREAD

**Issue by palica** [haxmeister/funtoo-reporter#112]
I would like to add a comment with current version of tool to the config file when generated through --update-config

**Comment by ShadowM00n** [comment]
Should be trivial. I'll take care of it.

**Comment by ShadowM00n** [comment]
I think that should do it. Let me know if I overlooked anything.

**Comment by palica** [comment]
is funtoo-report -l using only uncommented lines?

```
cat /etc/funtoo-report.conf 
# Generated on Sat Apr 14 22:41:17 2018 for v2.0.0-136-gcc83c96 of funtoo-report
UUID:d9c85d92-b59d-43f2-9d96-dafd576d3525
boot-dir-info:y
hardware-info:y
installed-pkgs:y
kernel-info:y
kit-info:y
profile-info:y
```

```
funtoo-report -l
Current configuration of /etc/funtoo-report.conf:

UUID: d9c85d92-b59d-43f2-9d96-dafd576d3525
boot-dir-info: y
hardware-info: y
installed-pkgs: y
kernel-info: y
kit-info: y
profile-info: y
```
Would it make sense to show the comment also when using -l|--list-config?

**Comment by ShadowM00n** [comment]
I'm not sure it would, as that command serves as a test that everything is being parsed correctly as much as anything else, to my understanding, and it calls on user_config() directly, which skips comments.

**Comment by tejr** [comment]
I agree with @ShadowM00n -- the option isn't much use if you get the same result by `cat /etc/funtoo-report.conf`. Its primary use is showing what the module has parsed from the config.

**Comment by palica** [comment]
ok, fine.

looks good IMHO and can be merged to develop.
