### ISSUE TITLE
funtoo-report options in the report

### ISSUE THREAD

**Issue by palica** [haxmeister/funtoo-reporter#116]
Could we add to the report what options are enabled for the tool? So basically funtoo-report --list-config

**Comment by ShadowM00n** [comment]
I don't see any statistical value in this. If users choose to not share specific parts, they may have a variety of reasons or even none at all, and we can already tell what was shared or not shared in a given report by simply looking at it.

**Comment by palica** [comment]
true, but could also have some stale settings still active -> that would show us that they don't run funtoo-report --update-config and would either print some message or update the ebuild.

**Comment by ShadowM00n** [comment]
If there are old settings, they won't take effect at all, so a changed name would result in no data showing up. One way to handle that is to explicitly look for every single config option when parsing it and print a local message telling them to update the file, then exiting. If that is wanted, that should be doable, but I see no reason to report on that.

**Comment by palica** [comment]
I like the idea of @ShadowM00n "One way to handle that is to explicitly look for every single config option when parsing it and print a local message telling them to update the file, then exiting."

That would probably be better.

**Comment by ShadowM00n** [comment]
Sounds good then. I guess I'll try out that self-assign button and do that this week.

**Comment by ShadowM00n** [comment]
See https://github.com/haxmeister/funtoo-reporter/commit/f48e41d8916f16e93b30569da137aeb06fcceaed. I forgot to mention this issue by name, but there you go.
