### ISSUE TITLE
add version for reporter tool :)

### ISSUE THREAD

**Issue by palica** [haxmeister/funtoo-reporter#12]
report also the version of _self to elasticsearch.

**Comment by haxmeister** [comment]
the version of reporter or of the report?

**Comment by palica** [comment]
version of the program

**Comment by haxmeister** [comment]
"version" key has been added to the body of the report.. I'm assuming thats were we want it and not necessarily in the header that tells elasticsearch were to index it too. Let me know if I'm mistaken, otherwise it's there now.

**Comment by palica** [comment]
looks like elasticsearch doesn't care as where the value is, does it?

**Comment by haxmeister** [comment]
well there are certain params that are in the code like _id etc.. those get passed in the json like a header that es is looking for. I'm not entirely certain how many of these es looks for. the data that we parsed off the machine is going in _body for instance. I think in es _body shows up as _code.
