### ISSUE TITLE
zsh completion

### ISSUE THREAD

**Issue by palica** [haxmeister/funtoo-reporter#121]
if we do bash we might try to do zsh

**Comment by tejr** [comment]
I'm willing to learn how to do this, but I don't know how Zsh completion works (yet).

**Comment by palica** [comment]
does this help?
https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org

**Comment by palica** [comment]
ok, tested and it works on my system. going to merge into develop.
