### ISSUE TITLE
bump_version new function

### ISSUE THREAD

**Issue by palica** [haxmeister/funtoo-reporter#128]
opening discussion here.

vision: 
we would add `Next-release yyyy-mm-dd` to the `Changes` file and before releasing we would run `./bump_version.sh` and that would find the string add the correct version here and "today's" date.

what do you think?

**Comment by palica** [comment]
basically changing this line https://github.com/haxmeister/funtoo-reporter/blob/2938dc9fd86ac3bc12f64910732380830eeb62d1/Changes#L3 to `3.1.0 2018-04-24`

**Comment by ShadowM00n** [comment]
I don't think I really see a point, especially if we're mostly manually writing that file to begin with.

**Comment by palica** [comment]
ok
