### ISSUE TITLE
bash completion warning during emerge

### ISSUE THREAD

**Issue by Bluebottle-new** [haxmeister/funtoo-reporter#148]
Funtoo-Report installs fine but prints following warning before the install part:

`  Problems with installed bash completions were found:
  
       funtoo-report: incorrect name, no completions for 'funtoo-report' command defined.
       ': missing alias (symlink) for completed command.
  
 
 For more details on installing bash-completions, please see:
 https://wiki.gentoo.org/wiki/Bash/Installing_completion_files`

**Comment by palica** [comment]
is this gentoo or funtoo?

**Comment by palica** [comment]
ok, I am able to reproduce. will look into it.

**Comment by palica** [comment]
tested 814d601 and it fixes the bug. there will be a bug-fix release shortly available.

**Comment by palica** [comment]
new ebuild coming shortly - this will fix the issue. @Bluebottle-new  please test with 3.2.2 once in tree. and report back.

**Comment by Bluebottle-new** [comment]
The warning is gone now. Thanks.
