### ISSUE TITLE
option for config update

### ISSUE THREAD

**Issue by palica** [haxmeister/funtoo-reporter#27]
funtoo-report config-update

would do something like this:
1. save UUID if present
2. delete the file
3. create new file with all config values
4. insert saved UUID

**Comment by haxmeister** [comment]
should this ask the y or n value for each item as it generates a new config?

**Comment by palica** [comment]
that would be cool too (ask for each value). but a plain regen and a notice to check the file is also fine if you don't want to play with it that much.

**Comment by palica** [comment]
Oleg, asked to change /etc/report.conf to /etc/funtoo-report.conf we could put these two things together.

somehow :)

thanks
