### ISSUE TITLE
metricbeat uses daily indices

### ISSUE THREAD

**Issue by palica** [haxmeister/funtoo-reporter#31]
```
health status index                       uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   .kibana                     oebrJgJRSwCqXfStiq976w   1   1        136            3    248.9kb        248.9kb
yellow open   metricbeat-6.1.3-2018.02.15 ei2ExkE-TzuPdAHfnX1j6w   1   1      31358            0      4.2mb          4.2mb
yellow open   metricbeat-6.1.3-2018.02.16 86ehcmY1RUiBXN_BmkKhwg   1   1      32024            0      8.6mb          8.6mb
yellow open   funtoo                      h5oFubTFToedNaibqn3IRQ   5   1        109            2      6.1mb          6.1mb
```
this is the output from indices on ES. metricbeat uses daily rotated indices. I don't know what the advantage to this would be. Also don't know how to post index structure with the data. main concern is the timestamp field be indexed as number or text field and not as time.

will do some more research.maybe we could do monthly indices.

**Comment by palica** [comment]
OK, so this is the proposal for changes:

````
            # load params for elastic search into report
            index => 'funtoo-201x.0y', 
            type  => 'report',
````
1. change index to monthly or maybe even **weekly** index so for this week it would be 
index => 'funtoo-2018.07'

I don't know what the performance implications are having a larger index. So theoretically if 100 users report every hour => 2400 reports a day => 16800 report a week => 67200 a month.

Going weekly will give us probably good balance between size/performance.
<hr>

2. change the type => 'report'
<hr>

3. and change the timestamp output format to:


"2018-02-16T11:14:48+01:00"

output from date on my system
```
root@latitudos ~ # ❯❯❯ date
Fri Feb 16 11:14:46 CET 2018
root@latitudos ~ # ❯❯❯ date -u
Fri Feb 16 10:14:48 UTC 2018

```

reference:
http://www.joda.org/joda-time/apidocs/org/joda/time/format/ISODateTimeFormat.html#dateOptionalTimeParser--

> ES Help:
> Date formats can be customised, but if no format is specified then it uses the default:
> 
> "strict_date_optional_time||epoch_millis"
> 

If I submit epoch time it doesn't get recognised as date, but as number instead. That's why changing it to date'T'time[offset] is necessary.

Thank you in advance.

**Comment by haxmeister** [comment]
I think I have this right.. look at the new timestamp and report header(which now has dynamic index value)

**Comment by palica** [comment]
works good, can be closed.
