### ISSUE TITLE
make the tool leaner - remove unneeded modules

### ISSUE THREAD

**Issue by palica** [haxmeister/funtoo-reporter#42]
I have heard a lot of feedback about Funtoo::Reporter using Search::Elasticsearch and that the installation pulls ~60 dependencies for a simple reporting tool.

Would be good if we could evaluate the options how to remove unneeded modules.

What are your thoughts about this?

**Comment by haxmeister** [comment]
yeah.. this currently uses the official elasticsearch module that is produced by ES themselves... maybe we can change this up to use curl or http::tiny possibly. I'll need a ES to send junk reports too until I get it just right.

**Comment by palica** [comment]
going to setup elk2.liguros for you to experiment same port and stuff just on elk2. let me know if you need anything.

**Comment by palica** [comment]
up and running ....

**Comment by haxmeister** [comment]
elk2 accepts the report using HTTP::Tiny but it doesn't overwrite the previous report.. is that because it isn't quite set up the same or is there something that needs to be changed on my end?

**Comment by palica** [comment]
I think it is OK. The UUID is the same and _id get setup from ES and that allows to monitor changes in time.
