### ISSUE TITLE
Restructure disk information to appease ELK

### ISSUE THREAD

**Issue by tejr** [haxmeister/funtoo-reporter#46]
Per discussion with @haxmeister about these two lines in `get_filesystem_info()`:

https://github.com/haxmeister/funtoo-reporter/blob/91bd29090d785d885d0966c2fa1c94aedea12f61/lib/Funtoo/Report.pm#L411-L412

It turns out these lines were intended as a defensive attempt to avoid an error raised by submitting the data directly from `lsblk --json` output:

> haxmeister: the error I see is " elastic search has limited support for arrays"
> haxmeister: but I didn't see the actual error until after those changes

We now suspect that this error is being raised not because of strings with square brackets in them, but because the section generated by this function (and other sections) includes arrayrefs of hashrefs:

```
   "blockdevices": [
      {"name": "fd0", "maj:min": "2:0", "rm": "1", "size": "4K", "ro": "0", "type": "disk", "mountpoint": null},
      {"name": "sda", "maj:min": "8:0", "rm": "0", "size": "111.8G", "ro": "0", "type": "disk", "mountpoint": null,
         "children": [
            {"name": "sda1", "maj:min": "8:1", "rm": "0", "size": "243M", "ro": "0", "type": "part", "mountpoint": "/boot"},
            {"name": "sda2"...
```

It was suggested that we instead translate this to a hashref structure, perhaps something like this:

```
   "blockdevices": {
      "fd0": {"name": "fd0", "maj:min": "2:0", "rm": "1", "size": "4K", "ro": "0", "type": "disk", "mountpoint": null},
      "sda": {"name": "sda", "maj:min": "8:0", "rm": "0", "size": "111.8G", "ro": "0", "type": "disk", "mountpoint": null,
         "children": {
            "sda1": {"name": "sda1", "maj:min": "8:1", "rm": "0", "size": "243M", "ro": "0", "type": "part", "mountpoint": "/boot"},
            "sda2": {"name": "sda2"...
```

This is straightforward to do and I'm willing to try it.

**Comment by haxmeister** [comment]
This looks really good.. I'm going to close this. Hopefully we will get more information about how these data structure  changes are work with ES
