### ISSUE TITLE
Decide on structure for hardware information

### ISSUE THREAD

**Issue by tejr** [haxmeister/funtoo-reporter#47]
The `get_lspci()`, `get_hardware_info()`, `get_chassis_info()`, and `get_netinfo()` functions are retrieving information from the `/sys` filesystem about devices for the report. In fact, `get_filesystem_info()` is indirectly also using information from this filesystem, because the `lsblk` call appears to read from `/sys` to get its information.

Per recommendation from @haxmeister, it may make more sense to put everything retrieved from `/sys` pertaining to hardware information into one section of the report with key `hardware` and consolidate the functions that use this filesystem together. We may even also want to fold anything retrieved from `/proc` or `/dev` under that same section.

**Comment by haxmeister** [comment]
This can be good because the internal data structure for these functions can be a single structure instead of a unique structure for each function. It's also a golden opportunity to remove system calls and some system deps.

**Comment by palica** [comment]
I like the changes and how this is shaping up. Perfect work all of you guys!

ES seems still unhappy about the Objects in Array like it is submitted for hardware-info.video
 {
  "Driver": "radeon",
  "Class": "VGA compatible controller",
  "Device": "ES1000",
  "Rev": "02",
  "SDevice": "ES1000",
  "SVendor": "Hewlett-Packard Company",
  "Vendor": "Advanced Micro Devices, Inc. [AMD/ATI]",
  "Slot": "01:03.0"
}

Could we change this to something like filesystem-info? 
hardware-info.video.driver "radeon"

And could we change 
blockdevices.sdx.size to a number (removing the M,G like in 1024M ...)?

What are your thoughts?

**Comment by tejr** [comment]
> Could we change this to something like filesystem-info?
> hardware-info.video.driver "radeon"

Yes, although if there were more than one card with `Driver` value `radeon`, one would have to supplant the other. If we used `Slot`, though, it could be unique, like we did for `Name`. Is that still useful?

No hash-munging devilry would be required here as we build our own with @ShadowM00n's code (probably the best person to do this).

> And could we change
> blockdevices.sdx.size to a number (removing the M,G like in 1024M ...)?

Easily... just add `-b` to `lsblk`. I'll do that now.

**Comment by haxmeister** [comment]
So we take a structure like this:

```
"hardware-info" : {
      "video" : [
         {
            "Module" : "i915",
            "Driver" : "i915",
            "Class" : "VGA compatible controller",
            "Device" : "Mobile 4 Series Chipset Integrated Graphics Controller",
            "SDevice" : "Mobile 4 Series Chipset Integrated Graphics Controller",
            "Slot" : "00:02.0",
            "SVendor" : "Hewlett-Packard Company",
            "Rev" : "09",
            "Vendor" : "Intel Corporation"
         }
      ],
      "sound" : [
         {
            "Vendor" : "Intel Corporation",
            "Rev" : "03",
            "SVendor" : "Hewlett-Packard Company",
            "Slot" : "00:1b.0",
            "SDevice" : "82801I (ICH9 Family) HD Audio Controller",
            "Device" : "82801I (ICH9 Family) HD Audio Controller",
            "Class" : "Audio device",
            "Driver" : "snd_hda_intel",
            "Module" : "snd_hda_intel"
         }
      ]
   }
```
and change it too something like this?

```
"hardware-info" : {
      "video" : {
           "00:02.0" : {
                "Module" : "i915",
                "Driver" : "i915",
                "Class" : "VGA compatible controller",
                "Device" : "Mobile 4 Series Chipset Integrated Graphics Controller",
                "SDevice" : "Mobile 4 Series Chipset Integrated Graphics Controller",
                "SVendor" : "Hewlett-Packard Company",
                "Rev" : "09",
                "Vendor" : "Intel Corporation"
             }
      },
      "sound" : {
         "00:1b.0" : {
                "Vendor" : "Intel Corporation",
                "Rev" : "03",
                "SVendor" : "Hewlett-Packard Company",
                "SDevice" : "82801I (ICH9 Family) HD Audio Controller",
                "Device" : "82801I (ICH9 Family) HD Audio Controller",
                "Class" : "Audio device",
                "Driver" : "snd_hda_intel",
                "Module" : "snd_hda_intel"
             }
         "00:1c.0" : {
                "Vendor" : "Whatever",
                "Rev" : "03",
                "SVendor" : "Hewlett-Packard Company",
                "SDevice" : "82801I (ICH9 Family) HD Audio Controller",
                "Device" : "82801I (ICH9 Family) HD Audio Controller",
                "Class" : "Audio device",
                "Driver" : "snd_hda_intel",
                "Module" : "snd_hda_intel"
             }
          }
       }
```

**Comment by haxmeister** [comment]
after last commit:
```
   "hardware-info" : {
      "Video" : {
         "00:02.0" : {
            "Device" : "Mobile 4 Series Chipset Integrated Graphics Controller",
            "Driver" : "i915",
            "SVendor" : "Hewlett-Packard Company",
            "Module" : "i915",
            "Vendor" : "Intel Corporation",
            "Rev" : "09",
            "SDevice" : "Mobile 4 Series Chipset Integrated Graphics Controller",
            "Class" : "VGA compatible controller"
         }
      },
      "Audio" : {
         "00:1b.0" : {
            "Device" : "82801I (ICH9 Family) HD Audio Controller",
            "Driver" : "snd_hda_intel",
            "SVendor" : "Hewlett-Packard Company",
            "ProgIf" : "20",
            "Module" : "snd_hda_intel",
            "Vendor" : "Intel Corporation",
            "Rev" : "03",
            "Class" : "Audio device",
            "SDevice" : "82801I (ICH9 Family) HD Audio Controller"
         }
      }
   },

```

**Comment by haxmeister** [comment]
now all hardware is in a combined structure.. also removed items from config file that were combined under "hardware". Seems far less confusing to sort through now.

**Comment by haxmeister** [comment]
This will mean the data structure is quite different when reported to ES so will need palica to see that it is usable this way.

**Comment by tejr** [comment]
Yep, that's what I meant, that was quick! Hopefully it suits ES's way of doing things.
