### ISSUE TITLE
combine package information

### ISSUE THREAD

**Issue by haxmeister** [haxmeister/funtoo-reporter#49]
I'm thinking it may be appropriate to also combine information about installed packages into a single data structure since it's the really the same type of information anway:

create a structure called "packages" and fill it as follows:

```
packages{
    @system{}       # packages in the system set
    @world{}          # packages in world set
    custom-sets     # packages that are in a custom made set
    additional{}       # packages not found in any set (deps?)
}
```
let me know if this makes sense... and I need to know from palica if this is a structure you can make sense of using ES

**Comment by haxmeister** [comment]
This could eliminate the call to eqeury potentially also, which would significantly shorten the time it takes to generate the report. I know speed is not a high priority but it is a bonus side effect.

**Comment by tejr** [comment]
I didn't notice the existing `equery` call when I was working on the `get_version_info` sub that finds installed versions of software. Given that it's retrieving the entire list of packages installed, that code could definitely be consolidated.

What would we do instead of the `equery --list` call to get the package list? Crawl through the ebuild dirs?

**Comment by ShadowM00n** [comment]
As I look over this and the output presently reported from the tool, I kind of wonder if we're overdoing it just a bit here.

Right now, it seems that we're reporting on both the packages in general as well as the packages marked as world (with no de-duplication presently), and it is proposed that we further break it down into other categories (potentially *with* de-duplication in this case, I assume). My question is simply "why"?

If the overall idea of the project is a statistical report, I'm not certain I see the value of such at present. While I could very easily be overlooking something, it seems that if we merely want this data for a popularity contest, a single canonical list ought to be sufficient. We could even determine version information of select packages from this list as easily as we could from the file system. The only use of a more complex system that comes to mind is perhaps assuming that anything not in world was not installed "purposefully", but that isn't a very safe assumption for a number of reasons, and I don't think it's a good idea to second-guess user intent based off of it.

My idea, assuming the above is true, is to get a list of installed packages, and then integrate them into the "get specific program versions" work, and not worry overmuch about overall categorisation.

Thoughts?

**Comment by palica** [comment]
I agree here with @ShadowM00n. I think for the statistics of this tool it is good to get the installed packages and probably the versions so the testing of the most used packages/versions would take place for example before a major branch (1.0-prime => 1.2-prime) switch or something along these lines.

It would be probably good to get the packages in @custom-sets (doesn't have to be separate category, but can). Going to think about it little bit more.

**Comment by haxmeister** [comment]
I'll leave this issue up pending further thoughts for a while. My thinking was that packages that are in a set have unique importance to the user. For instance the @system set which if modified, would be a deviation from the standard funtoo tool chain correct? Also there seemed to be some value in knowing packages that commonly are put in a custom set. It has bugged me that we are double reporting packages by not comparing the 3 data structures we have already. It is redundant to have a section that reports gcc versions but also have gcc and version info reported in the list of all installed packages. This was the root of my thinking. However, the purpose is to create a data structure that is easily usable in ES.. that is the first and highest priority. Anything else is just entertainment for bored programmers..lol

**Comment by tejr** [comment]
This is probably best decided by people using Funtoo as a "daily driver" and know what would and wouldn't be valuable in the report. I'm happy to help implement whatever you gents decide.

**Comment by ShadowM00n** [comment]
@haxmeister I asked around in IRC and found something interesting: the @system set is derived from a handful of files, and it's not strictly meant to be user-modifiable -- it's a toolset for the developers more than anything else. Anyone modifying that would need to create their own special profile and know what they're doing. Something to think about in light of all this.

According to one, you can find most or all of the packages by running "find /var/git/meta-repo/kits/*/profiles -name packages".

**Comment by haxmeister** [comment]
Output from ShadoM00n's code showing a data structure for packages that does not use arrays. The structure contains slot number as a key and version number as a value. 
``` json
{
'x11-libs/gksu' => {
                              0 => '2.0.2-r2'
                           },
'x11-libs/gtk+' => {
                             2 => '2.24.31',
                             3 => '3.20.10'
                           }
}
```
in ES table this would look like:
```
'x11-libs/gksu'.0.'2.0.2-r2'
'x11-libs/gtk+'.2.'2.24.31'
'x11-libs/gtk+'.3.'3.20.10'
```
This eliminates the array of package names that is evidently hard to search in ES perl Palica. However after some discussion I'm wondering if it might be easier to search through in ES if the slot number was last since the natural inclination is to search for package-version not package-slot-version.
``` json
{
'x11-libs/gksu' => {
                              '2.0.2-r2' =>0
                           },
'x11-libs/gtk+' => {
                             '2.24.31' => 2,
                             '3.20.10' => 3
                           }
}
```
Looking at Palica for input on this one. ShadowM00n can easily tweak the code to produce either structure as the difficult part is really done.

**Comment by palica** [comment]
I like the slot at the end better. Can we just test it, I don't know how ES will behave with this one.

**Comment by palica** [comment]
here is some reference from ES about Arrays, maybe a good read for you guys?
https://www.elastic.co/guide/en/elasticsearch/reference/current/array.html

**Comment by ShadowM00n** [comment]
@palica That documentation suggests to me that using a different datatype on the ES side would fix the issue, but I'm not entirely sure.

That said, I have the slots at the end now and can make a pull request whenever.

However, I have one last concern with this for the moment: do we still want/need get_version_info()? I re-wrote it while I was doing all of this to make use of an array containing all the ebuilds so it wouldn't have to gather it from the filesystem again, and it's still using its old format. If all that's fine, I'm content to leave it as-is, and if it is now rendered effectively obsolete by the new formatting, @tejr has mentioned he's fine seeing it removed. Just need to come to a decision one way or another.

**Comment by palica** [comment]
Yes, I have the same feeling array => nested
https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html

If the new all_packages_installed_with_versions() function works as expected with ES, then I could just search for the core/system packages and it would also be more dynamic (I can change the packages without need to change the get_version_info code) and independent of the code. If that makes sense.

I would say, lets abandon the get_version_info and try with the new code, if it works good, if not ... bad, I suppose.

**Comment by ShadowM00n** [comment]
Made a pull request. Let's see what happens.

**Comment by haxmeister** [comment]
we will stall this work, as we want to make a new release that does not contain this new structure for pkgs but the old structure from previous release

**Comment by haxmeister** [comment]
I think we can now go back and add this change to the develop branch. @ShadowM00n if you want to take the reigns on this one since you have most recently thought it through. Let's get that package data structure unified again :dancing_women:

**Comment by palica** [comment]
please add this change to a separate feature branch @ShadowM00n

**Comment by ShadowM00n** [comment]
Pushed to alternative-getall branch; review at your leisure.

**Comment by palica** [comment]
let's get this also to develop. good to go!

**Comment by palica** [comment]
merged = closing
