### ISSUE TITLE
bytes from filesystem without quotes

### ISSUE THREAD

**Issue by palica** [haxmeister/funtoo-reporter#52]
c39d7da65a535d49426dd6c94a2ca0eed8edea83

there are some comments for this commit, basically the quotes around filesize make ES think it is a string and it won't change in near future probably, so it would be nice if you could work around it somehow.

Thank you

**Comment by haxmeister** [comment]
this is an easy fix.. just have to force the type

**Comment by tejr** [comment]
This seems to do the trick on my test machine.
