### ISSUE TITLE
Verify exports are actually required for Funtoo::Reporter

### ISSUE THREAD

**Issue by tejr** [haxmeister/funtoo-reporter#56]
Most of the methods in `Funtoo::Reporter` are marked as `@EXPORT_OK` using `Exporter`.

Is this necessary? `funtoo-report` does not specify any functions in its `use` statement for the module; instead, it specifies the fully-qualified path to each method (a good thing).

If exports aren't actually needed, we can knock out `use Exporter` and the list of `@EXPORT_OK` subroutines. Commenting these out as a test doesn't seem to break anything.

**Comment by haxmeister** [comment]
You caught me... using exporter was because of my ignorance about making perl modules work and should probably just disappear if it's not needed. I had originally intended to have a proper interface but a lib of functions is fine for our application
