### ISSUE TITLE
improve command line options

### ISSUE THREAD

**Issue by haxmeister** [haxmeister/funtoo-reporter#57]
Need to select and add a core module to handle command line args, that will make it easier to add new options like just outputting certain data or other options that make it possible to use this as a diagnostic tool more easily.

**Comment by tejr** [comment]
[`Getopt::Long`](https://metacpan.org/pod/Getopt::Long) was discussed. It's core since forever, and should do at least most of what we need. Despite its name it does support short alternatives to options, e.g. `-f` vs `--force`.

**Comment by tejr** [comment]
In debugging the HTTP submission errors in issue #61, I added a `Getopt::Long` option to `funtoo-report` called `--debug` or `-d` in commit 1ed7dae. All it does at present is print the response body content from the form submission, but it seemed like a good start.

We should definitely add a `--help`/`-h`, at the very least.

**Comment by haxmeister** [comment]
let's make the old args (show-json and send etc..) into a compatibility function and make a modern alternative using the getopts lib. That will get the code for the old args out of our faces a little bit and clean things up for the addition of new options easily. The code is getting a little too complicated in funtoo-report, I think this will help quite a bit. What do you think @tejr ?

**Comment by tejr** [comment]
Well sure, if you'd prefer an option calling convention, although supporting both methods of arguments (I imagine you mean `--show-json` as well as just `show-json`) would make things more complex, not less. Is there a specific part of the script that's becoming bloated?

**Comment by ShadowM00n** [comment]
This has been implemented in a separate branch, docs-and-options.

**Comment by palica** [comment]
branch merged to develop, waiting for release. should we close?

**Comment by tejr** [comment]
@palica: I reckon.
