### ISSUE TITLE
Decide on how fatal failed `open` and `opendir` calls are

### ISSUE THREAD

**Issue by tejr** [haxmeister/funtoo-reporter#58]
The code in `Funtoo::Reporter` as it is varies in how it reacts to a failed file `open` or directory `opendir`, sometimes dying immediately, other times warning and continuing.

In `get_net_info()` in commit e5f5b91, @ShadowM00n introduced an import of [`use autodie`](https://metacpan.org/pod/autodie) with its `:io` mode. We should consider whether failing to open any file at all is fatal, or if partially complete/correct submissions are acceptable.

If we should always `die`, then we can use `autodie` at the top of the file and remove a lot of boilerplate in the code. If we shouldn't always `die`, then we should probably not import it at all and instead be explicit everywhere.

**Comment by haxmeister** [comment]
I'm inclined to not `die` and instead actually produce error output. This way we can diagnose the report itself and still get some bit of output in a report. I have also considered that users might set the report as a cron job like our test machines. With that in mind it might also be wise to create a data structure in the report itself. Then the dev team would be aware possibly before the user is. Unless the error is in sending the actual report. 

1. Produce error output
2. Create a section in the report itself for errors in the tool

Each section should probably return an empty hash if there are errors while pushing the error message onto perhaps a global array? and also to stderr

**Comment by tejr** [comment]
Yep, if partial reports are still desirable, as long as there's explicit error output that sounds sensible.

> Each section should probably return an empty hash if there are errors

The `undef` value might make a bit more semantic sense, but maybe that would make ElasticSearch choke when it gets translated to JSON `null` ... @palica ?

**Comment by palica** [comment]
I like this idea => Create a section in the report itself for errors in the tool
That would allow us (you coders :) to work on such errors and fix them.

ES can handle `null` without problem I think like in this filesystem report.

```
      "filesystem": {
        "blockdevices": {
          "sdb": {
            "size": 1000204886016,
            "hotplug": "1",
            "parttype": null,
            "rm": "0",
            "fstype": null,
            "children": {
              "sdb1": {
                "name": "sdb1",
                "mountpoint": "/run/media/palica/1adbbe8b-a935-4073-badc-7c91c1265cfd",
                "tran": null,
                "parttype": "0fc63daf-8483-4772-8e79-3d69d8477de4",
                "fstype": "ext2",
                "rm": "0",
                "size": 1000203820544,
                "hotplug": "1"
              }
```

**Comment by tejr** [comment]
All right, I'm happy with that approach. I'll adjust the error behaviour for `master` as it stands and work with @ShadowM00n as necessary to merge it in with what he's doing.

**Comment by haxmeister** [comment]
Still need to add this to get_net_info() and get_all_installed_pkg().

Sorry I squashed your self assignment.. didn't realize what I had done till I had already pushed... if it breaks your code you can back pedal this commit and push yours in @tejr

**Comment by tejr** [comment]
No problem at all @haxmeister, I hadn't even started; what you've done looks great.

**Comment by ShadowM00n** [comment]
I guess for the record I'll point out that I added such a thing to get_all_installed_pkg() and also introduced what is amounting to a carp/warn/croak/die replacement in the structure of it and in the form of a new sub, push_error(). As that seems to have been accepted, I guess that implies it needs to be pushed back into the other subs.

**Comment by haxmeister** [comment]
This method is set.. looks really nice!
