### ISSUE TITLE
Prepare for 1.4 Release

### ISSUE THREAD

**Issue by haxmeister** [haxmeister/funtoo-reporter#64]
without  @ShadowM00n's new pkginfo function in place for the purposes of putting out there a release that doesn't require that obnoxious elasticsearch module.

**Comment by haxmeister** [comment]
the current code in main is a candidate for release. Could everyone take a look that it all appears to be functioning as intended please?

1. Check the readme reflects what the program actually does.
2. Check that the data structure being sent to ES is proper and close enough to previous it will be an easy transition.
3. Check that the configuration file and the function that generates it correspond with the actual data that is reported.

I missed something I'm sure.. if you have a moment to pull this code and test it please do. Note that the code is currently set to 'elk' instead of 'elk2' and if you 'send' it will send to the production ES server instead of the test server.

**Comment by tejr** [comment]
I made a set of tweaks linked above to the README and to comments in the code. They are all really tiny changes, except for documenting `-d`/`--debug` (which is my bad).

I have not changed any of the code. I ran it and tested it with different sections as you requested and it seemed to work really well for me.

As far as I can tell, I'm happy for release unless anyone finds some show-stoppers.

**Comment by tejr** [comment]
Also, I missed your closing note about the production server switch, very sorry! My UUID is `c29866b5-7265-4b71-9d06-bf12b2bfb6c8` if you want to remove the test data I submitted from my Funtoo VM.

**Comment by haxmeister** [comment]
Released 1.4

**Comment by tejr** [comment]
Awww yeah!

**Comment by tejr** [comment]
We have become aware of a miscommunication about requirements for the 1.4 release with one of the developers, and @haxmeister has chosen to remove the v1.4 tag. We are back in pre-release state.
