### ISSUE TITLE
Switch to git flow structure

### ISSUE THREAD

**Issue by haxmeister** [haxmeister/funtoo-reporter#65]
Implement git flow structure and train developers to use it properly and safely

**Comment by palica** [comment]
showing basic usage of dev-vcs/git-flow from portage
```
usage: git flow <subcommand>

Available subcommands are:
   init      Initialize a new git repo with support for the branching model.
   feature   Manage your feature branches.
   bugfix    Manage your bugfix branches.
   release   Manage your release branches.
   hotfix    Manage your hotfix branches.
   support   Manage your support branches.
   version   Shows version information.
   config    Manage your git-flow configuration.
   log       Show log deviating from base branch.
```

```git flow init
Initialized empty Git repository in /root/git-flow/.git/
No branches exist yet. Base branches must be created now.
Branch name for production releases: [master]
Branch name for "next release" development: [develop]

How to name your supporting branch prefixes?
Feature branches? [feature/]
Bugfix branches? [bugfix/]
Release branches? [release/]
Hotfix branches? [hotfix/]
Support branches? [support/]
Version tag prefix? []
Hooks and filters directory? [/root/git-flow/.git/hooks]
```

starting a new feature:
```
git flow feature start pkg-info                                                                                                                                             
Switched to a new branch 'feature/pkg-info'

Summary of actions:
- A new branch 'feature/pkg-info' was created, based on 'develop'
- You are now on branch 'feature/pkg-info'

Now, start committing on your feature. When done, use:

     git flow feature finish pkg-info
```

**Comment by palica** [comment]
![](http://nvie.com/img/git-model@2x.png)

**Comment by tejr** [comment]
I like `git flow` a lot, but I'm pretty new to it myself and it would be best to introduce it in stages. The single major important part we're missing right now is a `develop` branch that is allowed to be broken at any given time, where `master` isn't. I think we should start there and slowly flesh out the model including the fancy tagging stuff as we can read and teach one other.

**Comment by palica** [comment]
I agree with you @tejr. Are you guys up to it @haxmeister and @ShadowM00n ?

One more thing is in this article:
https://coderwall.com/p/7aymfa/please-oh-please-use-git-pull-rebase

This get rid of extra merge in the history.

**Comment by tejr** [comment]
I am actually OK with merge commits if something is actually being merged (i.e. the paths diverged at all), but I reckon it's pretty much a detail at this point.

I'll make a start on some sort of suggested structure in the next couple of days -- busy IRL, I'm afraid.

**Comment by haxmeister** [comment]
yes we need to definitely separate development from main.. I think that is a good start.. If we can do that, then myself and @ShadowM00n can learn how to submit to the dev branch appropriately. Baby steps for me at least, it's all 100% new to me and I've used the web interface to do things I wasn't sure about from the terminal like our last release. I think if we communicate a lot about it we will be ok.

**Comment by tejr** [comment]
OK, how about this: we get 1.4 "out the door", tag it, and then fork from that very commit into a new GitHub branch on `haxmeister/funtoo` called `develop`. We all start working on that branch, helping one another with the appropriate `git` arcana, and get used to just that first. We only merge back into master once we have another release, so every commit on `master` from the 1.4 tag onwards is itself a tagged release on a merge commit.

Once we're all confident, we can review making feature, hotfix, and release branches.

What do you think? @palica I am just as keen as you to get the full `git flow` system going, but I think we will need to pace ourselves.

**Comment by tejr** [comment]
All right, it looks like 2.0.0 is out the door. Congratulations, everyone!

The following what I suggest as a starting point. Let me know if any of this doesn't work for anyone.

I have branched from the v2.0.0 tag into a new branch on `haxmeister` called [`develop`](https://github.com/haxmeister/funtoo-reporter/tree/develop). From now on, this is where we make all new direct commits, pull requests, and feature merges. We ideally *never* commit directly to `master` from now on, instead only merging in from `develop`.

To do this, create a new branch in your local repositories called `develop`, and configure it to track `haxmeister`'s `develop` branch. The below assumes that you're using his repository as your `origin`.

```
$ git fetch --all
$ git rebase
$ git branch develop origin/develop
$ git checkout develop
```

This should mean that from now on, every time you do `git fetch --all` and then `git rebase` (or just `git pull`) on your local `develop` branch, you get all the latest developments, and `push` back to it too, leaving `master` untouched.

When you make (and when @haxmeister accepts) GitHub pull requests, you will need to be careful that you request they be merged into his `develop`, and not the `master`.

Once we've got everyone comfortable with that, we'll figure out whether we need the "release branches" thing. Does that make sense to everyone?

**Comment by tejr** [comment]
I've just made a [really simple commit here](https://github.com/haxmeister/funtoo-reporter/commit/06a36b3c1d94c5649d0ad5e8e7cd93d2e48c9214) on the `develop` branch to demonstrate.

**Comment by palica** [comment]
Good! Version 2.0.0 released - congratulations to you folks!

So let's move to git flow. You have already made the first step  develop branch. I strongly suggest using this dev-vcs/git-flow (https://github.com/petervanderdoes/gitflow-avh) helper as already mentioned somewhere. It just makes the whole thing easier, without having to do all the steps manually, like rebasing, merging and so on.

References:
- https://github.com/petervanderdoes/gitflow-avh#git-flow-usage
- https://danielkummer.github.io/git-flow-cheatsheet/

Should I write a small howto?

**Comment by tejr** [comment]
> Should I write a small howto?

If you like, but I am pretty sure everyone will need to get used to using the development branch first.

**Comment by haxmeister** [comment]
I've been trying to create a feature branch when I'm working with some success.. exception being an accidental submission to master.. thank you @tejr for fixing that back. 

been doing:
```git checkout -b my-new-branch```

then when I ```git push``` it reminds me I need to make the branch on the remote server. This is good because I otherwise would forget that fact, it also tells you exactly the command you need to issue.

I still need to learn how to make pull request from command line from my feature branch to development branch though.. so for my next lesson, feel free to give a short tutorial here @palica . Just make it about that.. don't tell me too much ... baby steps!

**Comment by palica** [comment]
Now we just need to use it. 
https://github.com/haxmeister/funtoo-reporter/wiki/Using-git-flow
