### ISSUE TITLE
support funtoo-report version

### ISSUE THREAD

**Issue by palica** [haxmeister/funtoo-reporter#77]
to show the installed version

**Comment by tejr** [comment]
How's this? #79

**Comment by haxmeister** [comment]
The installed version as an ARG or in the report?

**Comment by tejr** [comment]
@haxmeister: I understood @palica to mean supporting a new subcommand `funtoo-reporter version`, which is what I implemented in the now-merged #79. Perhaps I was wrong.

**Comment by palica** [comment]
yes I wanted to be able to quickly check the installed version using the cli without having to submit or run show-json
