### ISSUE TITLE
check before sending to ES if UUID really not empty

### ISSUE THREAD

**Issue by palica** [haxmeister/funtoo-reporter#78]
I had one of my machines after upgrade to 2.0.0 report with a blank UUID => not good :)

**Comment by palica** [comment]
although unable to reproduce anymore

**Comment by tejr** [comment]
This should do the trick. I can trigger it by intentionally deleting the line with the `UUID` key from `/etc/funtoo-report.conf`.

**Comment by palica** [comment]
thanks
