### ISSUE TITLE
Make ES submission URL configurable

### ISSUE THREAD

**Issue by tejr** [haxmeister/funtoo-reporter#81]
For development machines, it would be useful to define the server to which reports should be submitted either in the configuration file or directly on the command line, instead of hard-coding it in `funtoo-report`. This would allow easy testing without having to make changes to tracked files during development (and without having to remember to do so). I think putting it in the configuration file would be best, something like this:

```
ESurl:http://elk2.liguros.net:9200

boot-dir-info:y
hardware-info:y
installed-pkgs:y
kernel-info:y
kit-info:y
profile-info:y
version-info:y
world-info:y

# A unique identifier for this reporting machine
UUID:4a6886fa-5795-47e4-a1d3-d2fab05b59b5
```

Coupled with issue #82, I think this would make testing and development a fair bit easier.

**Comment by tejr** [comment]
@haxmeister, @ShadowM00n: What do you think? (I see @palica has given this a thumbs-up.)

**Comment by haxmeister** [comment]
this has been swallowed by issue #86
