### ISSUE TITLE
should the program autocheck if newer version exists and ask user to upgrade?

### ISSUE THREAD

**Issue by palica** [haxmeister/funtoo-reporter#83]
for example after send or any other funtoo-report command run?

**Comment by haxmeister** [comment]
I can do this.. would we be checking available versions in GIT repo or portage?

**Comment by tejr** [comment]
I think this would best be a separate command again, maybe something like `check-update`. I think the user should be able to continue running a non-git version if they wish to without being nagged on every run. The function itself in #84 is fine by me.

**Comment by haxmeister** [comment]
do you think we should have it check and push-error() any time the tool is run, but only report when the user issues an ARG?

**Comment by tejr** [comment]
@haxmeister: My vote is no. I don't think GitHub should be contacted unless the user specifically requests exactly that.

**Comment by palica** [comment]
probably check with portage is sufficient and maybe also only on submission error

**Comment by haxmeister** [comment]
ok I'm not sure how to move forward with this now.. I removed the code I had added regarding this since it wasn't what was intended. However I'm not sure what kind of output we are thinking about here. What shall I do with the information about available versions? also are we talking the same output you might get from ```emerge -s Funtoo-Report | grep latest``` ?

**Comment by ShadowM00n** [comment]
For my part, I think this is a pointless endeavor; as a semi-official tool, people are going to be getting this through portage anyway, and unless they specifically pin a certain version/block future updates, they'll tend to get them as soon as the Funtoo people update them. The nag therefore doesn't benefit us or them at all, in my  view.

**Comment by palica** [comment]
ok, let's close it.
