### ISSUE TITLE
show-json should not output errors

### ISSUE THREAD

**Issue by haxmeister** [haxmeister/funtoo-reporter#85]
Some convention needs to be made as to when it is acceptable to show non fatal errors. Since show-json is potentially an API for other softwares, it should only do as it says and just so a json structure. Error output should be suppressed here since a calling program would expect only json.

**Comment by tejr** [comment]
I summon ... @ShadowM00n!

**Comment by ShadowM00n** [comment]
This is most likely a non-issue. All errors are printed to STDERR, and piped output typically only handles STDOUT.

**Comment by haxmeister** [comment]
If you have checked to make sure we don't have any bare "print" statements in the error code and all errors are going to STDERR then we can definitely close this issue. I'll check back for affirmative from @ShadowM00n or @tejr before closing.. or @tejr can close it if he confirms in IRC.

**Comment by ShadowM00n** [comment]
All errors that use my sub use STDERR, but there are indeed "bare" print statements sprinkled throughout the code; they are related to the configuration or to sending the json report, so I left them alone. I do not believe they should normally trigger during show-json unless the configuration is broken, which is something that needs to be dealt with before the data can be gathered to begin with.
