### ISSUE TITLE
v3.0.0

### ISSUE THREAD

**Issue by tejr** [haxmeister/funtoo-reporter#89]
Earlier today, @palica requested a new release for ease of Ebuild management:

```
11:15:59 <palica> can we do a release with man pages?
11:16:20 <palica> so I don't have to hack ebuild to do pod2man only for 9999
11:16:36 <tejr> palica: fine by me; 2.1.0, maybe
11:17:04 <palica> 2.1.0 is fine with me
```

Should we release a v2.1.0?

**Comment by palica** [comment]
maybe wait for the new index names? and couple of other features. we don't have to rush it.

**Comment by haxmeister** [comment]
New index names are in development branch.. anything else we want to sneak in?

**Comment by palica** [comment]
give me a list :)

**Comment by palica** [comment]
OK, so I think after https://github.com/haxmeister/funtoo-reporter/pull/95 gets merged this can be our new 2.1.0-rc1. And after we test it for couple of hours or a day on develop, this can be then our new 2.1.0 release.

Thank you all for the hard work!

**Comment by palica** [comment]
On first look this (https://github.com/haxmeister/funtoo-reporter/compare/develop?expand=1) also looks good. The only blocker would be maybe https://github.com/haxmeister/funtoo-reporter/issues/94.

**Comment by haxmeister** [comment]
so adding the new filesystem structure and the new get-all package structure sounds like a major release wouldn't you say? 

With that in mind, how are we on the docs and options?.. because last I looked our options were completely different from the last release.. that also looks like a major version bump. Considering the work that is happening now, is a 2.1.0 release opportunity blown by?

**Comment by tejr** [comment]
My vote is for a 3.0.0, since we completely changed the way everything works and this makes that unambiguously clear.

**Comment by palica** [comment]
I am ok with going to 3.0.0 - since (yes) once again we break a lot of things :)  like send => -s etc.

**Comment by palica** [comment]
once all stuff here https://github.com/haxmeister/funtoo-reporter/milestone/1
gets addressed we can release a BIG one :)
great job people!

**Comment by haxmeister** [comment]
new filesystem structure and get-all-pkgs structure have been merged. Nothing now but tweaks and testing etc..

**Comment by palica** [comment]
thank you for all you hard work guys!
