### ISSUE TITLE
add support for https:// submission

### ISSUE THREAD

**Issue by palica** [haxmeister/funtoo-reporter#91]
the port stays the same (9200).

**Comment by haxmeister** [comment]
Best I can tell we just need to add 2 dependencies but other than that the code should work the way it is. Only need to change the http to https in the submission link. It appears that the error must be on the server end, best I can tell.

**Comment by tejr** [comment]
This is done in the `hotfix-2.0.1` branch presently pending merging into `master` in pull request #92. Just requires @haxmeister's acceptance.

Note the two new dependencies `IO::Socket::SSL` and `Net::SSLeay` in `Makefile.PL`; this may mean we require new Perl packages for the ebuild's dependencies.

**Comment by tejr** [comment]
Merged!
