### ISSUE TITLE
Server Security

### ISSUE THREAD

**Issue by haxmeister** [haxmeister/funtoo-reporter#93]
Secure the ES administration and/or adapt submission code appropriately.

**Comment by palica** [comment]
So the first part securing elk on submission port is done.

```
curl -XDELETE https://elk.liguros.net:9200/funtest
401 Unauthorized
```

Which methods are actually needed by the reporter? I have HEAD, GET, POST, PUT enabled.

The second part is to secure kibana frontend.

**Comment by haxmeister** [comment]
we are currently using POST only :
```perl
my $response = $http->request( 'POST', $url, \%options );
```

**Comment by palica** [comment]
I might have a solution for kibana frontend. Take a look at https://liguros.net
I am embedding an iframe.
Could this work? Or is it just security/obscurity?

**Comment by haxmeister** [comment]
iframe is just a webpage shown through a window. It is just obscurity. For the browser to view the iframe contents, they must also be able to view the page within the frame.. even separately.

**Comment by palica** [comment]
OK, so for now Kibana is secured and ES submission should not allow DELETE method.
