### ISSUE TITLE
slim down hardware-info.filesystem.blockdevices

### ISSUE THREAD

**Issue by palica** [haxmeister/funtoo-reporter#94]
```
              "blockdevices": {
                "sda": {
                  "tran": "sas",
                  "fstype": null,
                  "rm": "0",
                  "mountpoint": null,
                  "parttype": null,
                  "hotplug": "0",
                  "children": {
                    "sda1": {
                      "parttype": "0x82",
                      "mountpoint": "[SWAP]",
                      "fstype": "swap",
                      "tran": null,
                      "rm": "0",
                      "name": "sda1",
                      "size": 1073741824,
                      "hotplug": "0"
                    }
                  },
```

from all of these values we probably want 
blockdevices: tran, hotplug?
children: parttype, fstype, size

mountpoint can reveal for example username for /run/media/user/mounts
see this report for example:
https://elk.liguros.net/app/kibana#/doc/2a09d340-2b5d-11e8-b2f1-8d70db01ab55/fundev-2.1.0-alpha-2018.03.22/report/?id=4Td9TmIBFi5WzroWOMKO

[![image.png](https://s18.postimg.org/ooxoh0imx/image.png)](https://postimg.org/image/6m4lpsms5/)

discuss please.

**Comment by palica** [comment]
this is adding also a massive number of fields (had to bump index.mapping.total_fields.limit value)
because every sdX (8 fields) + sdXn (8 fields) (more levels possible for example bcache/btrfs, ...)
so a disk with 4 partitions adding 32 fields, if more disks present like 4 disk - 128 fields just for hdd info => too much

we have to think about a better structure for this.

**Comment by palica** [comment]
I would say, let's add some summary of the found information.

For the statistics it is probably nice to know. 

1. how many disks at all (number)
2. what connection (sata, sas ...)
3. size of the disks (combined)
4. fstype (btrfs, ext4 ...)

**Comment by haxmeister** [comment]
Maybe this is closer?


```json
"blockdevices": {
     "sda": {
          "tran": "sas",
          "fstype": null,
          "total-size":1231234343,
          "children": {
               "sda1": {
                    "fstype": "swap",
                }
           }
     }
     "sdb": {
          "tran": "sas",
           "fstype": null,
           "total-size":1231234343,
           "children": {
                "sdb1": {
                     "fstype": "swap",
                 }
            }
     }
}
```

**Comment by palica** [comment]
I would maybe do it even less. Don't know if this is a valid json structure:
```
"blockdevices": {
     "device-count": 2,
     "tran": ["sas", "sata"],
      "fstype": ["btrfs", "ext4", "xfs", "swap"] , #combination of all unique fstypes from all devices
       "total-size":1231234343, #combined for all devices or as haxmeister has done it per device
}
```

**Comment by tejr** [comment]
What if we flattened it completely?

```
"blockdevices": {
     "device-count": 4,
     "sda": {
          "tran": "sas",
          "fstype": null,
          "size": 1231234343
     },
     "sda1": {
         "fstype": "swap",
         "size": 1231234343
     },
     "sdb": {
         "tran": "sas",
         "size": 1231234343,
         "fstype": null
     },
     "sdb1": {
         "fstype": "swap",
         "size": 1231234343
     }
}
```

**Comment by palica** [comment]
I think we need to flatten the flattened so from your proposal:
```
blockdevices:
  device-count: 2
  tran: sas
  fstype: [swap, ext4]

and maybe
  sdd: null
  hdd: 2
```
counting sda, sdb => 2
fstype: unique list of used fstypes
tran: unique list of tran(sport?)

**Comment by haxmeister** [comment]
check branch feature/filesystems and see if this is flat enough... 
from my simple laptop:

```json
      "filesystem" : {
         "sr0" : {
            "fstypes" : [
               null
            ],
            "children" : 0,
            "size" : "1073741312"
         },
         "device-count" : 2,
         "sda" : {
            "fstypes" : [
               "ext2",
               "swap",
               "ext4"
            ],
            "children" : 3,
            "size" : "750156374016"
         }
      }

```

**Comment by haxmeister** [comment]
so far from my funtoo container:
```json
{
   "hardware-info" : {
      "filesystem" : {
         "device-count" : 8,
         "sde" : {
            "tran" : "sas",
            "size" : 4000787030016,
            "children" : 2,
            "fstypes" : [null, null]
         },
         "sr0" : {
            "tran" : "ata",
            "size" : 660406272,
            "children" : 0,
            "fstypes" : [null]
         },
         "sdd" : {
            "tran" : "sas",
            "size" : 4000787030016,
            "fstypes" : [null, null ],
            "children" : 2
         },
         "sdf" : {
            "tran" : "sas",
            "size" : 4000787030016,
            "children" : 2,
            "fstypes" : [null, null ]
         },
         "sda" : {
            "children" : 3,
            "fstypes" : [null, null, null],
            "size" : 1024209543168,
            "tran" : "sas"
         },
         "sdb" : {
            "fstypes" : [null, null ],
            "children" : 2,
            "tran" : "sas",
            "size" : 4000787030016
         },
         "nvme0n1" : {
            "fstypes" : [null,  null ],
            "children" : 2,
            "tran" : "nvme",
            "size" : 280065171456
         },
         "sdc" : {
            "fstypes" : [null, null ],
            "children" : 2,
            "size" : 1024209543168,
            "tran" : "sas"
         }
      }
}
```

from my much more simple laptop:
```json
{
      "filesystem" : {
         "device-count" : 2,
         "sda" : {
            "size" : 750156374016,
            "tran" : "sata",
            "fstypes" : ["ext2", "swap", "ext4"],
            "children" : 3
         },
         "sr0" : {
            "fstypes" : [null],
            "tran" : "sata",
            "children" : 0,
            "size" : 1073741312
         }
      }
}
```

**Comment by haxmeister** [comment]
Let me know if it should/could be even flatter than this.. curious what this might look like on other more complex file systems.

**Comment by haxmeister** [comment]
could also remove stats on each individual device and just have it something like this:
```json
{
     "filesystems" :{
          "device-count" : 8,
          "tran-types" : ["sata", "nvme"],
          "total-size" : 12312455345243,
          "fstypes" : ["ext2", "swap", "ext4"]
     }
}
```

**Comment by tejr** [comment]
Perhaps we should start reviewing this by figuring out exactly what information is required in the report, and what's junk that can be discarded. Is the primary goal simply to find out how many filesystems the user has and how much space they have? Or is it more complicated than that? That is to say, do we actually care about block devices, or are we interested in filesystems?

**Comment by palica** [comment]
Well, I think it is kind of interesting to know what users are using with funtoo? Are they on ssd/hdd/nvme, using sata drives or enterprise sas? what is the size of ssd, hdd, something else? What filesystems are in use?

I would be happy with as few as https://github.com/haxmeister/funtoo-reporter/issues/94#issuecomment-375591954

**Comment by haxmeister** [comment]
Tried to make it show futures as key and size as values because I think that's the simplest overview of relevant info, but there are null fstypes that have caused heartaches in the attempt. I suppose it is better to make a database of fstypes to accumulate the data too...

**Comment by haxmeister** [comment]
just pushed perhaps the flattest code possible:

from my simple laptop:
```json
     "filesystem" : {
         "tran-types" : {
            "sata" : 1
         },
         "fstypes" : {
            "ext4" : 747873624064,
            "swap" : 2147483648,
            "ext2" : 134217728
         },

```
From my much more complex container which reports all "null" file system types with lsblk for some reason:
```json
   "hardware-info" : {
      "filesystem" : {
         "tran-types" : {
            "nvme" : 1,
            "sas" : 6
         },
         "fstypes" : {
            "Null" : 271474171392
         },
         "device-count" : 7

```

**Comment by palica** [comment]
I like it, let me test it and we can merge it.

**Comment by tejr** [comment]
>Does it make sense? Objections?

None here.

**Comment by haxmeister** [comment]
the output you posted:

```json
"filesystem": {
        "device-count": 6,
        "fstypes": {
          "Null": 1048576,
          "btrfs": 60019441664,
          "zfs_member": 3999175540736,
          "swap": 1610423808
        },
        "tran-types": {
          "sata": 6
        }
```
shows exactly what your asking for unless I'm misunderstanding. Shows 6 devices, 6 of them are SATA, there are 4 file system types including one reporting as "null", each file system type is followed by the combined sum of the size of all devices/children of the same type. So in this example ZFS file system has a combined size of 
```
"zfs_member": 3999175540736
```
If the information is not what you want, you will have to explain to me more clearly what your expecting to see.

**Comment by palica** [comment]
ok, I was basically asking to display the sum of for example zfs_member so since there are 4 disks with 3999175540736 this would show the size: 16TB 

can I extend it to show this then?

```
"filesystem": {
        "device-count": 6,
        "fstypes": {
          "btrfs-size": 60019441664,
          "btrfs-count": 1,
          "zfs_member-size": 15999175540736, #combined size from all members (member1 + member2 ...)
          "zfs_member-count": 4,
          "swap-size": 1610423808 #again sum of swap partitions
          "swap-count": 4 #number of children 
        },
        "tran-types": {
          "sata": 6
        }
```

**Comment by palica** [comment]
count number of partitions of the same type
and
count size of partitions of same size

**Comment by haxmeister** [comment]
@palica please keep me updated on this issue.. I think it is most certainly to do with ES in some way. The data structure is valid in all tests I know of.

**Comment by palica** [comment]
yes, will do

**Comment by palica** [comment]
I think this can be closed for now.

**Comment by palica** [comment]
let's merge it to develop, I think this is ready.

**Comment by haxmeister** [comment]
this has merged into develop
