### ISSUE TITLE
can we add some more logic to cli options

### ISSUE THREAD

**Issue by palica** [haxmeister/funtoo-reporter#99]
for example when selecting funtoo-report -j -u 

tool shows json and then runs update-config. 

does excluding -u with -s or -j options make sense?

**Comment by tejr** [comment]
> ShadowM00n: if you're not too invested, I'll take care of the config-related things
> ShadowM00n: the alt-config and the logic/combination thing
> tejr: go for it, i was going to do it this evening if you didn't get to it first, as i suspected you might be interested
> tejr: all i was going to do was delay the executing of the actual action until all the options had been parsed
> tejr: there may be a Smarter way
> tejr: once it works it's a big win for testability, which i'm looking forward to

**Comment by ShadowM00n** [comment]
I've implemented certain priority levels in https://github.com/haxmeister/funtoo-reporter/pull/96 as part of the issue there.

**Comment by tejr** [comment]
@palica: There's a whole lot of goodness related to this merged in via #96, now. Does it do everything you want?

**Comment by palica** [comment]
also good to go! can we change -V | --version to be able to have -v | --verbose once it gets implemented, please?

**Comment by palica** [comment]
merged, V|version changed = closing
